from track import Track, timedelta
t1 = Track('Blinding Lights', 'The Weeknd', 'After Hours', timedelta(minutes=3, seconds=20))
t2 = Track('Watermelon Sugar', 'Harry Styles', 'Fine Line', timedelta(minutes=2, seconds=6))
t3 = Track('Levitating', 'Dua Lipa', 'Future Nostalgia', timedelta(minutes=3, seconds=23))
t4 = Track('Shape of You', 'Ed Sheeran', '÷ (Divide)', timedelta(minutes=4, seconds=23))
t5 = Track('Good 4 U', 'Olivia Rodrigo', 'SOUR', timedelta(minutes=3, seconds=14))
t6 = Track('Stay', 'The Kid LAROI & Justin Bieber', 'F*CK LOVE 3: OVER YOU', timedelta(minutes=2, seconds=35))
t7 = Track('Peaches', 'Justin Bieber', 'Justice', timedelta(minutes=3, seconds=17))
t8 = Track('Kiss Me More', 'Doja Cat feat. SZA', 'Planet Her', timedelta(minutes=3, seconds=24))
t9 = Track('Save Your Tears', 'The Weeknd', 'After Hours', timedelta(minutes=3, seconds=35))
t10 = Track('Montero (Call Me By Your Name)', 'Lil Nas X', 'Montero', timedelta(minutes=2, seconds=17))
t11 = Track('Stay', 'The Kid LAROI & Justin Bieber', 'F*CK LOVE 3: OVER YOU', timedelta(minutes=2, seconds=35))
t12 = Track('Peaches', 'Justin Bieber', 'Justice', timedelta(minutes=3, seconds=17))
t13 = Track('Kiss Me More', 'Doja Cat feat. SZA', 'Planet Her', timedelta(minutes=3, seconds=24))
t14 = Track('Save Your Tears', 'The Weeknd', 'After Hours', timedelta(minutes=3, seconds=35))
t15 = Track('Montero (Call Me By Your Name)', 'Lil Nas X', 'Montero', timedelta(minutes=2, seconds=17))
t16 = Track('Levitating', 'Dua Lipa', 'Future Nostalgia', timedelta(minutes=3, seconds=23))
t17 = Track('Blinding Lights', 'The Weeknd', 'After Hours', timedelta(minutes=3, seconds=20))
t18 = Track('Watermelon Sugar', 'Harry Styles', 'Fine Line', timedelta(minutes=2, seconds=6))
t19 = Track('Shape of You', 'Ed Sheeran', '÷ (Divide)', timedelta(minutes=4, seconds=23))
t20 = Track('Good 4 U', 'Olivia Rodrigo', 'SOUR', timedelta(minutes=3, seconds=14))
t21 = Track('Bad Habits', 'Ed Sheeran', '=', timedelta(minutes=3, seconds=50))
t22 = Track('Good Days', 'SZA', 'Good Days', timedelta(minutes=4, seconds=36))
t23 = Track('Deja Vu', 'Olivia Rodrigo', 'SOUR', timedelta(minutes=4, seconds=2))
t24 = Track('Leave The Door Open', 'Bruno Mars & Anderson .Paak', 'An Evening with Silk Sonic', timedelta(minutes=4, seconds=2))
t25 = Track('Cold Heart', 'Elton John & Dua Lipa', 'The Lockdown Sessions', timedelta(minutes=3, seconds=22))
t26 = Track('Industry Baby', 'Lil Nas X & Jack Harlow', 'Montero', timedelta(minutes=3, seconds=32))
t27 = Track('Take My Breath', 'The Weeknd', 'After Hours', timedelta(minutes=3, seconds=38))
t28 = Track('Happier Than Ever', 'Billie Eilish', 'Happier Than Ever', timedelta(minutes=4, seconds=59))
t29 = Track('Shivers', 'Ed Sheeran', '=', timedelta(minutes=3, seconds=27))
t30 = Track('Midnight City', 'M83', 'Hurry Up, We\'re Dreaming', timedelta(minutes=4, seconds=3))
1
2
3
listofTracks = [t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20, t21, t22, t23, t24, t25, t26, t27, t28, t29, t30]