from track import Track, Duration
t1 = Track('Blinding Lights', 'The Weeknd', 'After Hours', Duration(minute=3, sec=20))
t2 = Track('Watermelon Sugar', 'Harry Styles', 'Fine Line', Duration(minute=2, sec=6))
t3 = Track('Levitating', 'Dua Lipa', 'Future Nostalgia', Duration(minute=3, sec=23))
t4 = Track('Shape of You', 'Ed Sheeran', '÷ (Divide)', Duration(minute=4, sec=23))
t5 = Track('Good 4 U', 'Olivia Rodrigo', 'SOUR', Duration(minute=3, sec=14))
t6 = Track('Stay', 'The Kid LAROI & Justin Bieber', 'F*CK LOVE 3: OVER YOU', Duration(minute=2, sec=35))
t7 = Track('Peaches', 'Justin Bieber', 'Justice', Duration(minute=3, sec=17))
t8 = Track('Kiss Me More', 'Doja Cat feat. SZA', 'Planet Her', Duration(minute=3, sec=24))
t9 = Track('Save Your Tears', 'The Weeknd', 'After Hours', Duration(minute=3, sec=35))
t10 = Track('Montero (Call Me By Your Name)', 'Lil Nas X', 'Montero', Duration(minute=2, sec=17))
t11 = Track('Stay', 'The Kid LAROI & Justin Bieber', 'F*CK LOVE 3: OVER YOU', Duration(minute=2, sec=35))
t12 = Track('Peaches', 'Justin Bieber', 'Justice', Duration(minute=3, sec=17))
t13 = Track('Kiss Me More', 'Doja Cat feat. SZA', 'Planet Her', Duration(minute=3, sec=24))
t14 = Track('Save Your Tears', 'The Weeknd', 'After Hours', Duration(minute=3, sec=35))
t15 = Track('Montero (Call Me By Your Name)', 'Lil Nas X', 'Montero', Duration(minute=2, sec=17))
t16 = Track('Levitating', 'Dua Lipa', 'Future Nostalgia', Duration(minute=3, sec=23))
t17 = Track('Blinding Lights', 'The Weeknd', 'After Hours', Duration(minute=3, sec=20))
t18 = Track('Watermelon Sugar', 'Harry Styles', 'Fine Line', Duration(minute=2, sec=6))
t19 = Track('Shape of You', 'Ed Sheeran', '÷ (Divide)', Duration(minute=4, sec=23))
t20 = Track('Good 4 U', 'Olivia Rodrigo', 'SOUR', Duration(minute=3, sec=14))
t21 = Track('Bad Habits', 'Ed Sheeran', '=', Duration(minute=3, sec=50))
t22 = Track('Good Days', 'SZA', 'Good Days', Duration(minute=4, sec=36))
t23 = Track('Deja Vu', 'Olivia Rodrigo', 'SOUR', Duration(minute=4, sec=2))
t24 = Track('Leave The Door Open', 'Bruno Mars & Anderson .Paak', 'An Evening with Silk Sonic', Duration(minute=4, sec=2))
t25 = Track('Cold Heart', 'Elton John & Dua Lipa', 'The Lockdown Sessions', Duration(minute=3, sec=22))
t26 = Track('Industry Baby', 'Lil Nas X & Jack Harlow', 'Montero', Duration(minute=3, sec=32))
t27 = Track('Take My Breath', 'The Weeknd', 'After Hours', Duration(minute=3, sec=38))
t28 = Track('Happier Than Ever', 'Billie Eilish', 'Happier Than Ever', Duration(minute=4, sec=59))
t29 = Track('Shivers', 'Ed Sheeran', '=', Duration(minute=3, sec=27))
t30 = Track('Midnight City', 'M83', 'Hurry Up, We\'re Dreaming', Duration(minute=4, sec=3))
listofTracks = [t1, t2, t3, t4, t5, t6, t7, t8, t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20,t21,t22,t23,t24,t25,t26,t27,t28,t29,t30]